routes/web.php
<?php

use App\Http\Controllers\QuestionnaireController;
use Illuminate\Support\Facades\Route;

Route::name('guest.')->group(function () {
    Route::controller(QuestionnaireController::class)->group(function () {
        Route::get('/', 'index')->name('index');
        Route::post('/', 'store')->name('store');
        Route::get('results/{id}', 'show')->name('results');
    });
});

app/Models/Frequency.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Frequency extends Model
{
    /**
     * Returns associated submissions based off of a given frequency ID
     */
    public function submission(): HasMany
    {
        return $this->hasMany(Submission::class);
    }
}

app/Models/Submission.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Submission extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'frequency_id',
        'cohort',
        'name',
        'birthdate',
        'daily_frequencies',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'birthdate' => 'date',
        ];
    }

    /**
     * Returns the associated frequency with a given questionnaire
     */
    public function frequency(): BelongsTo
    {
        return $this->belongsTo(Frequency::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory;
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

abstract class Controller
{
    //
}

app/Http/Controllers/QuestionnaireController.php
<?php

namespace App\Http\Controllers;

use App\Models\Frequency;
use App\Models\Submission;
use Carbon\Carbon;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class QuestionnaireController extends Controller
{
    /**
     * Displays the questionnaire
     */
    public function index(): View
    {
        $data['frequencies'] = Frequency::query()->orderBy('id', 'desc')->get();
        return view('index', $data);
    }

    /**
     * Accepts and processes applicant form submissions
     */
    public function store(Request $request): RedirectResponse
    {
        $messages = [
            'name.required' => 'Your first name is required.',
            'frequency.required' => 'Migraine frequency is required.',
            'birthdate.required' => 'Your date of birth is required.',
        ];

        $request->validate([
            'name' => 'bail|required|max:18',
            'frequency' => 'required',
            'daily_frequency' => 'nullable|max:2',
            'birthdate' => 'required',
        ], $messages);

        // Validate the birth date
        $givenDate = Carbon::createFromFormat('Y-m-d', $request->input('birthdate'));
        $targetBirthDate = Carbon::now()->subYears(18)->format('Y-m-d');

        $dateCheck = ($givenDate < $targetBirthDate) ? true : false;

        if (!$dateCheck) {
            return redirect()->back()->withErrors(['msg' => 'Partcipants must be over 18 years of age']);
        }

        // Verify that the daily migration frequencies are more than 0
        if ($request->filled('daily_frequency') && $request->input('daily_frequency') == '0') {
            return redirect()->back()->withErrors(['msg' => 'Please select daily frequency total.']);
        }

        // Establish a new record for this submission
        $designatedCohort = $request->filled('daily_frequency') ? 'B' : 'A';
        $frequency = Frequency::where('slug', $request->input('frequency'))->first();
        $dailyFrequency = $request->filled('daily_frequency') ? $request->input('daily_frequency') : null;

        $submission = Submission::create([
            'frequency_id' => $frequency->id,
            'cohort' => $designatedCohort,
            'name' => $request->input('name'),
            'birthdate' => $givenDate,
            'daily_frequencies' => $dailyFrequency,
        ]);

        // Show the summary
        return redirect()->route('guest.results', ['id' => $submission->id]);
    }

    /**
     * Displays a summary of their submission
     */
    public function show(string $id): View
    {
        $data['results'] = Submission::find(intval($id));
        return view('results', $data);
    }
}

resources/views/index.blade.php
@extends('layout')
@section('content')
<section class="hero is-large herobg mb-6 is-hidden-touch">
    <div class="hero-body">
        <div class="columns is-mobile">
            <div class="column is-one-third-desktop is-half-tablet is-fullwidth-mobile">
                <div class="card bg-motif-blue has-shadow is-spaced">
                    <div class="card-content ">
                        <div class="content">                                         
                            <p class="title has-text-white pb-4">Migraines - Clinical Trial Registration</p>
                            <p class="subtitle has-text-white pb-2">Thank you for your interest in this clinical trial, we look forward to working with you. Participants must be a minimum of <strong class="has-text-white">18 years of age</strong> in order to participate.</p>
                            <p class="subtitle has-text-white">Please be sure to fill in the form in its entirety to gain instant results to your eligibility for participation.</p>
                        </div>
                    </div>
                </div>
            </div>            
        </div>        
    </div>
</section>

<section class="hero is-small is-info-dark mb-6 is-hidden-desktop" >
    <div class="hero-body">
        <div class="columns is-mobile">
            <div class="column is-fullwidth">
                <div class="card bg-motif-blue has-shadow is-spaced">
                    <div class="card-content ">
                        <div class="content">                                         
                            <p class="title has-text-white pb-4">Clinical Trial Eligibility Questionnaire</p>
                            <p class="subtitle has-text-white">Thank you for your interest in this clinical trial, we look forward to working with you. Please be sure to fill in the form in its entirety to gain instant results to your eligibility for participation.</p>
                        </div>
                    </div>
                </div>
            </div>            
        </div>        
    </div>
</section>
<section>
    <main class="container is-fluid">       

        <form method="POST" action="{{ route('guest.store') }}" class="mb-8 container is-max-desktop" enctype="application/x-www-form-urlencoded">
            @csrf

            <div id="app">
                @if ($errors->any())
                    <div class="has-background-danger-dark p-4">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li class="has-text-white-bis is-size-6">{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <submissionform :frequencies="{{ json_encode($frequencies) }}"></submissionform>
            </div>            
        </form>
    </main>
</section>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head prefix="og: https://ogp.me/ns#">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Umotif | Matt Webb Dev Test</title>
        <meta name="description" content="This dev test was done by Matt Webb. My last name is not indicative to my profession. It's just a coincidence.">
        <meta property="og:locale" content="en_US">
        <meta property="og:site_name" content="Umotif - Dev Test">
        @vite('resources/css/app.css')
        @vite('resources/js/app.js')
        <link rel="icon" href="https://umotif.com/wp-content/themes/umotif/img/favicon.svg" type="image/svg+xml">
    </head>
    <body>
    <x-header />
    
    <div>
        <!-- Start content -->

        @yield('content')

        <!-- End content -->
    
    </div>

    <x-footer />

    @stack('scripts')

    </body>
</html>    

resources/views/results.blade.php
@extends('layout')
@section('content')
<section class="hero is-primary mb-6">
    <div class="hero-body">
      <p class="title pb-2">Thank You!</p>
      <p class="subtitle">We have received your submitted information and will reach out to you in the near future. Here is a summary of your information.</p>
    </div>
  </section>
<section>
    <main class="container is-fluid">
        <div class="card">
            <div class="card-content">
                <div class="content">
                    <h1 class="is-size-2">Hello {{ ucfirst($results->name) }}!</h1>
                    <hr>
                    <p class="is-size-4 has-text-weight-semibold pb-4">Summary of Your Information</p>
                    <ul>
                        <li>Your date of birth is <u>{{ $results->birthdate->todatestring() }}</u></li>
                        <li>You are experiencing <u>{{ strtolower($results->frequency->name) }}</u> migraines.</li>
                        @if(!empty($results->daily_frequencies))
                            <li>You are experiencing <u>{{ $results->daily_frequencies }} migraines per day</u>.</li>
                        @endif
                        <li>Based on the frequency of your migraines, you would be part of <u>Cohort {{ $results->cohort }}.</u></li>
                      </ul>
                </div>
            </div>
        </div>
    </main>
</section>
@endsection